services:
  truefan:
    image: rocketplanner83/truefan:latest
    container_name: truefan
    restart: unless-stopped
    privileged: true
    working_dir: /app
    ports:
      - "5002:5002"
    environment:
      - TZ=America/Chicago
    volumes:
      - /sys:/sys
      - /dev:/dev
      - /etc/sensors3.conf:/etc/sensors3.conf:ro
